apiVersion: v2
name: metrics-server
description: Kubernetes Metrics Server
version: 0.1.0
type: application
dependencies:
  - name: metrics-server
    version: "3.12.x"
    repository: "https://kubernetes-sigs.github.io/metrics-server"
