{{- range $name, $config := .Values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/managed-by: kubarax
spec:
  provider:
    {{- toYaml $config.provider | nindent 4 }}
  {{- with $config.refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with $config.conditions }}
  conditions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
