apiVersion: v2
name: traefik
description: Traefik Kubernetes Ingress Controller
version: 0.1.0
type: application
dependencies:
  - name: traefik
    version: "39.x"
    repository: "https://traefik.github.io/charts"
