apiVersion: v2
name: cert-manager
description: Certificate management controller for Kubernetes
version: 0.1.0
type: application
dependencies:
  - name: cert-manager
    version: "v1.20.x"
    repository: "https://charts.jetstack.io"
