{{- range $name, $config := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/managed-by: kubarax
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $config.secretStoreRef.name }}
    kind: {{ $config.secretStoreRef.kind }}
  target:
    name: {{ $config.target.name }}
  data:
    {{- range $config.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
